export const mockProvincia = [
  { id: 1, nombre_provincia: "Havana" },
  { id: 2, nombre_provincia: "Santiago de Cuba" },
  { id: 3, nombre_provincia: "Villa Clara" },
  { id: 4, nombre_provincia: "Matanzas" },
  { id: 5, nombre_provincia: "Pinar del Río" }
];

export const mockMinisterio = [
  { id: 1, nombre_ministerio: "Ministerio de Salud" },
  { id: 2, nombre_ministerio: "Ministerio de Educación" },
  { id: 3, nombre_ministerio: "Ministerio de Agricultura" },
  { id: 4, nombre_ministerio: "Ministerio de Cultura" },
  { id: 5, nombre_ministerio: "Ministerio de Transporte" }
];

export const mockMunicipio = [
  { id: 1, provincia_id: 1, provincia: mockProvincia[0], nombre_municipio: "Plaza de la Revolución" },
  { id: 2, provincia_id: 1, provincia: mockProvincia[0], nombre_municipio: "Vedado" },
  { id: 3, provincia_id: 2, provincia: mockProvincia[1], nombre_municipio: "Santiago Centro" },
  { id: 4, provincia_id: 1, provincia: mockProvincia[0], nombre_municipio: "Centro Habana" },
  { id: 5, provincia_id: 2, provincia: mockProvincia[1], nombre_municipio: "Segundo Frente" },
  { id: 6, provincia_id: 3, provincia: mockProvincia[2], nombre_municipio: "Santa Clara" },
  { id: 7, provincia_id: 4, provincia: mockProvincia[3], nombre_municipio: "Varadero" },
  { id: 8, provincia_id: 5, provincia: mockProvincia[4], nombre_municipio: "Viñales" }
];

export const mockProveedor = [
  {
    id: 1,
    nombre: "Empresa de Suministros S.A.",
    codigo: "PRV001",
    telefonos: "555-0101",
    domicilio: "Calle Principal #123",
    municipio: mockMunicipio[0],
    ministerio: mockMinisterio[0],
    fechaCreacion: "2023-01-15",
    estado: "Activo",
    tipo: "Empresa Estatal",
    categoria: "Gubernamental"
  },
  {
    id: 2,
    nombre: "Servicios Educativos C.A.",
    codigo: "PRV002",
    telefonos: "555-0202",
    domicilio: "Avenida Central #456",
    municipio: mockMunicipio[1],
    ministerio: mockMinisterio[1],
    fechaCreacion: "2023-02-20",
    estado: "Activo",
    tipo: "Cooperativa",
    categoria: "Cooperativa"
  },
  {
    id: 3,
    nombre: "Constructora del Este",
    codigo: "PRV003",
    telefonos: "555-0303",
    domicilio: "Carrera 7 #789",
    municipio: mockMunicipio[2],
    ministerio: mockMinisterio[2],
    fechaCreacion: "2023-03-10",
    estado: "Inactivo",
    tipo: "Empresa Privada",
    categoria: "Privada"
  },
  {
    id: 4,
    nombre: "Consultoría Técnica Ltda.",
    codigo: "PRV004",
    telefonos: "555-0404",
    domicilio: "Plaza Mayor #321",
    municipio: mockMunicipio[0],
    ministerio: mockMinisterio[0],
    fechaCreacion: "2023-04-05",
    estado: "Activo",
    tipo: "Cooperativa",
    categoria: "Cooperativa"
  },
  {
    id: 5,
    nombre: "Eventos Culturales S.A.",
    codigo: "PRV005",
    telefonos: "555-0505",
    domicilio: "Calle Cultural #654",
    municipio: mockMunicipio[1],
    ministerio: mockMinisterio[1],
    fechaCreacion: "2023-05-15",
    estado: "Pendiente",
    tipo: "Empresa Privada",
    categoria: "Privada"
  },
  {
    id: 6,
    nombre: "Transportes Unidos",
    codigo: "PRV006",
    telefonos: "555-0606",
    domicilio: "Avenida Principal #987",
    municipio: mockMunicipio[2],
    ministerio: mockMinisterio[2],
    fechaCreacion: "2023-06-20",
    estado: "Activo",
    tipo: "Empresa Estatal",
    categoria: "Gubernamental"
  },
  {
    id: 7,
    nombre: "Cultura Varadero",
    codigo: "PRV007",
    telefonos: "789-012-3456",
    domicilio: "Avenida Playa, Varadero",
    municipio: mockMunicipio[6],
    ministerio: mockMinisterio[3],
    fechaCreacion: "2023-07-01",
    estado: "Activo",
    tipo: "Empresa Privada",
    categoria: "Privada"
  },
  { 
    id: 8, 
    municipio: mockMunicipio[7], 
    ministerio: mockMinisterio[2], 
    nombre: "Agricultura Viñales", 
    codigo: "PRV008", 
    telefonos: "890-123-4567", 
    domicilio: "Valle de Viñales",
    fechaCreacion: "2023-08-10",
    estado: "Pendiente",
    tipo: "Cooperativa",
    categoria: "Cooperativa"
  }
];

export const mockDepartamento = [
  { id: 1, nombre_dpto: "Recursos Humanos" },
  { id: 2, nombre_dpto: "Finanzas" },
  { id: 3, nombre_dpto: "IT" },
  { id: 4, nombre_dpto: "Operaciones" },
  { id: 5, nombre_dpto: "Logística" }
];

export const mockVigenciaContrato = [
  { id: 1, vigencia: 2023, alerta_vigencia: 30, tipo_alerta_vigencia: "Días" },
  { id: 2, vigencia: 2024, alerta_vigencia: 15, tipo_alerta_vigencia: "Días" },
  { id: 3, vigencia: 2025, alerta_vigencia: 10, tipo_alerta_vigencia: "Días" }
];

export const mockTipoContrato = [
  { id: 1, tipo_contrato: "Suministro" },
  { id: 2, tipo_contrato: "Servicios" },
  { id: 3, tipo_contrato: "Consultoría" }
];
  
  export const mockContrato = [
    {
      id: 1,
      vigencia: mockVigenciaContrato[0],
      proveedor: mockProveedor[0],
      tipo_contrato: mockTipoContrato[0],
      departamento: mockDepartamento[0],
      no_contrato: "CTR001",
      fecha_entrada: "2025-01-15",
      fecha_firmado: "2025-01-20",
      fecha_vencido: "2026-01-20",
      valor_cup: 100000,
      monto_vencimiento_cup: 20000,
      valor_cl: 90000,
      monto_vencimiento_cl: 18000,
      valor_usd: 4000,
      monto_vencimiento_usd: 800,
      observaciones: "Contrato activo",
      no_comite_contratacion: 1,
      fecha_comite_contratacion: "2025-01-10",
      no_acuerdo_comite_contratacion: 101,
      fecha_acuerdo_comite_contratacion: "2025-01-12",
      no_comite_administracion: 201,
      fecha_comite_administracion: "2025-01-14",
      monto_total: 150000,
      estado: "Activo"
    },
    {
      id: 2,
      vigencia: mockVigenciaContrato[1],
      proveedor: mockProveedor[1],
      tipo_contrato: mockTipoContrato[1],
      departamento: mockDepartamento[1],
      no_contrato: "CTR002",
      fecha_entrada: "2025-02-15",
      fecha_firmado: "2025-02-20",
      fecha_vencido: "2027-02-20",
      valor_cup: 200000,
      monto_vencimiento_cup: 40000,
      valor_cl: 180000,
      monto_vencimiento_cl: 36000,
      valor_usd: 8000,
      monto_vencimiento_usd: 1600,
      observaciones: "Contrato activo",
      no_comite_contratacion: 2,
      fecha_comite_contratacion: "2025-02-10",
      no_acuerdo_comite_contratacion: 102,
      fecha_acuerdo_comite_contratacion: "2025-02-12",
      no_comite_administracion: 202,
      fecha_comite_administracion: "2025-02-14",
      monto_total: 280000,
      estado: "Activo"
    },
    {
      id: 3,
      vigencia: mockVigenciaContrato[2],
      proveedor: mockProveedor[2],
      tipo_contrato: mockTipoContrato[2],
      departamento: mockDepartamento[2],
      no_contrato: "CTR003",
      fecha_entrada: "2023-03-15",
      fecha_firmado: "2023-03-20",
      fecha_vencido: "2026-03-20",
      valor_cup: 300000,
      monto_vencimiento_cup: 60000,
      valor_cl: 270000,
      monto_vencimiento_cl: 54000,
      valor_usd: 12000,
      monto_vencimiento_usd: 2400,
      observaciones: "Contrato activo",
      no_comite_contratacion: 3,
      fecha_comite_contratacion: "2023-03-10",
      no_acuerdo_comite_contratacion: 103,
      fecha_acuerdo_comite_contratacion: "2023-03-12",
      no_comite_administracion: 203,
      fecha_comite_administracion: "2023-03-14",
      monto_total: 450000,
      estado: "Activo"
    },
    {
      id: 4,
      vigencia: mockVigenciaContrato[0],
      proveedor: mockProveedor[0],
      tipo_contrato: mockTipoContrato[0],
      departamento: mockDepartamento[0],
      no_contrato: "CTR004",
      fecha_entrada: "2023-04-15",
      fecha_firmado: "2023-04-20",
      fecha_vencido: "2023-07-20",
      valor_cup: 40000,
      monto_vencimiento_cup: 8000,
      valor_cl: 36000,
      monto_vencimiento_cl: 7200,
      valor_usd: 1600,
      monto_vencimiento_usd: 320,
      observaciones: "Contrato activo",
      no_comite_contratacion: 4,
      fecha_comite_contratacion: "2023-04-10",
      no_acuerdo_comite_contratacion: 104,
      fecha_acuerdo_comite_contratacion: "2023-04-12",
      no_comite_administracion: 204,
      fecha_comite_administracion: "2023-04-14",
      monto_total: 50000,
      estado: "Activo"
    },
    {
      id: 5,
      vigencia: mockVigenciaContrato[1],
      proveedor: mockProveedor[1],
      tipo_contrato: mockTipoContrato[1],
      departamento: mockDepartamento[1],
      no_contrato: "CTR005",
      fecha_entrada: "2023-05-15",
      fecha_firmado: "2023-05-20",
      fecha_vencido: "2023-11-20",
      valor_cup: 60000,
      monto_vencimiento_cup: 12000,
      valor_cl: 54000,
      monto_vencimiento_cl: 10800,
      valor_usd: 2400,
      monto_vencimiento_usd: 480,
      observaciones: "Contrato activo",
      no_comite_contratacion: 5,
      fecha_comite_contratacion: "2023-05-10",
      no_acuerdo_comite_contratacion: 105,
      fecha_acuerdo_comite_contratacion: "2023-05-12",
      no_comite_administracion: 205,
      fecha_comite_administracion: "2023-05-14",
      monto_total: 75000,
      estado: "Activo"
    },
    {
      id: 6,
      vigencia: mockVigenciaContrato[2],
      proveedor: mockProveedor[2],
      tipo_contrato: mockTipoContrato[2],
      departamento: mockDepartamento[2],
      no_contrato: "CTR006",
      fecha_entrada: "2023-06-15",
      fecha_firmado: "2023-06-20",
      fecha_vencido: "2024-06-20",
      valor_cup: 140000,
      monto_vencimiento_cup: 28000,
      valor_cl: 126000,
      monto_vencimiento_cl: 25200,
      valor_usd: 5600,
      monto_vencimiento_usd: 1120,
      observaciones: "Contrato activo",
      no_comite_contratacion: 6,
      fecha_comite_contratacion: "2023-06-10",
      no_acuerdo_comite_contratacion: 106,
      fecha_acuerdo_comite_contratacion: "2023-06-12",
      no_comite_administracion: 206,
      fecha_comite_administracion: "2023-06-14",
      monto_total: 180000,
      estado: "Activo"
    },
    {
      id: 7,
      vigencia: mockVigenciaContrato[0],
      proveedor: mockProveedor[0],
      tipo_contrato: mockTipoContrato[0],
      departamento: mockDepartamento[0],
      no_contrato: "CTR007",
      fecha_entrada: "2023-07-15",
      fecha_firmado: "2023-07-20",
      fecha_vencido: "2025-07-20",
      valor_cup: 250000,
      monto_vencimiento_cup: 50000,
      valor_cl: 225000,
      monto_vencimiento_cl: 45000,
      valor_usd: 10000,
      monto_vencimiento_usd: 2000,
      observaciones: "Contrato activo",
      no_comite_contratacion: 7,
      fecha_comite_contratacion: "2023-07-10",
      no_acuerdo_comite_contratacion: 107,
      fecha_acuerdo_comite_contratacion: "2023-07-12",
      no_comite_administracion: 207,
      fecha_comite_administracion: "2023-07-14",
      monto_total: 320000,
      estado: "Activo"
    },
    {
      id: 8,
      vigencia: mockVigenciaContrato[1],
      proveedor: mockProveedor[1],
      tipo_contrato: mockTipoContrato[1],
      departamento: mockDepartamento[1],
      no_contrato: "CTR008",
      fecha_entrada: "2023-08-15",
      fecha_firmado: "2023-08-20",
      fecha_vencido: "2023-11-20",
      valor_cup: 35000,
      monto_vencimiento_cup: 7000,
      valor_cl: 31500,
      monto_vencimiento_cl: 6300,
      valor_usd: 1400,
      monto_vencimiento_usd: 280,
      observaciones: "Contrato activo",
      no_comite_contratacion: 8,
      fecha_comite_contratacion: "2023-08-10",
      no_acuerdo_comite_contratacion: 108,
      fecha_acuerdo_comite_contratacion: "2023-08-12",
      no_comite_administracion: 208,
      fecha_comite_administracion: "2023-08-14",
      monto_total: 45000,
      estado: "Activo"
    },
    {
      id: 9,
      vigencia: mockVigenciaContrato[2],
      proveedor: mockProveedor[2],
      tipo_contrato: mockTipoContrato[2],
      departamento: mockDepartamento[2],
      no_contrato: "CTR009",
      fecha_entrada: "2023-09-15",
      fecha_firmado: "2023-09-20",
      fecha_vencido: "2026-09-20",
      valor_cup: 400000,
      monto_vencimiento_cup: 80000,
      valor_cl: 360000,
      monto_vencimiento_cl: 72000,
      valor_usd: 16000,
      monto_vencimiento_usd: 3200,
      observaciones: "Contrato activo",
      no_comite_contratacion: 9,
      fecha_comite_contratacion: "2023-09-10",
      no_acuerdo_comite_contratacion: 109,
      fecha_acuerdo_comite_contratacion: "2023-09-12",
      no_comite_administracion: 209,
      fecha_comite_administracion: "2023-09-14",
      monto_total: 520000,
      estado: "Activo"
    },
    {
      id: 10,
      vigencia: mockVigenciaContrato[0],
      proveedor: mockProveedor[0],
      tipo_contrato: mockTipoContrato[0],
      departamento: mockDepartamento[0],
      no_contrato: "CTR010",
      fecha_entrada: "2023-10-15",
      fecha_firmado: "2023-10-20",
      fecha_vencido: "2024-01-20",
      valor_cup: 120000,
      monto_vencimiento_cup: 24000,
      valor_cl: 108000,
      monto_vencimiento_cl: 21600,
      valor_usd: 4800,
      monto_vencimiento_usd: 960,
      observaciones: "Contrato activo",
      no_comite_contratacion: 10,
      fecha_comite_contratacion: "2023-10-10",
      no_acuerdo_comite_contratacion: 110,
      fecha_acuerdo_comite_contratacion: "2023-10-12",
      no_comite_administracion: 210,
      fecha_comite_administracion: "2023-10-14",
      monto_total: 95000,
      estado: "Activo"
    }
  ];
  
  export const expiredContracts = [
    {
      id: 11,
      vigencia: mockVigenciaContrato[1],
      proveedor: mockProveedor[1],
      tipo_contrato: mockTipoContrato[1],
      departamento: mockDepartamento[1],
      no_contrato: "CTR011",
      fecha_entrada: "2022-11-01",
      fecha_firmado: "2022-11-05",
      fecha_vencido: "2024-11-05",
      valor_cup: 16000,
      monto_vencimiento_cup: 3200,
      valor_cl: 13000,
      monto_vencimiento_cl: 2600,
      valor_usd: 800,
      monto_vencimiento_usd: 160,
      observaciones: "Contrato vencido",
      no_comite_contratacion: 11,
      fecha_comite_contratacion: "2022-10-25",
      no_acuerdo_comite_contratacion: 111,
      fecha_acuerdo_comite_contratacion: "2022-10-27",
      no_comite_administracion: 211,
      fecha_comite_administracion: "2022-10-29",
      monto_total: 25000,
      estado: "Vencido"
    },
    {
      id: 12,
      vigencia: mockVigenciaContrato[2],
      proveedor: mockProveedor[2],
      tipo_contrato: mockTipoContrato[2],
      departamento: mockDepartamento[2],
      no_contrato: "CTR012",
      fecha_entrada: "2022-12-01",
      fecha_firmado: "2022-12-05",
      fecha_vencido: "2024-12-05",
      valor_cup: 17000,
      monto_vencimiento_cup: 3400,
      valor_cl: 14000,
      monto_vencimiento_cl: 2800,
      valor_usd: 850,
      monto_vencimiento_usd: 170,
      observaciones: "Consultoría vencida",
      no_comite_contratacion: 12,
      fecha_comite_contratacion: "2022-11-25",
      no_acuerdo_comite_contratacion: 112,
      fecha_acuerdo_comite_contratacion: "2022-11-27",
      no_comite_administracion: 212,
      fecha_comite_administracion: "2022-11-29",
      monto_total: 28000,
      estado: "Vencido"
    },
    {
      id: 13,
      vigencia: mockVigenciaContrato[0],
      proveedor: mockProveedor[0],
      tipo_contrato: mockTipoContrato[0],
      departamento: mockDepartamento[0],
      no_contrato: "CTR013",
      fecha_entrada: "2023-01-01",
      fecha_firmado: "2023-01-05",
      fecha_vencido: "2024-01-05",
      valor_cup: 18000,
      monto_vencimiento_cup: 3600,
      valor_cl: 15000,
      monto_vencimiento_cl: 3000,
      valor_usd: 900,
      monto_vencimiento_usd: 180,
      observaciones: "Suministro vencido",
      no_comite_contratacion: 13,
      fecha_comite_contratacion: "2022-12-25",
      no_acuerdo_comite_contratacion: 113,
      fecha_acuerdo_comite_contratacion: "2022-12-27",
      no_comite_administracion: 213,
      fecha_comite_administracion: "2022-12-29",
      monto_total: 30000,
      estado: "Vencido"
    },
    {
      id: 14,
      vigencia: mockVigenciaContrato[1],
      proveedor: mockProveedor[1],
      tipo_contrato: mockTipoContrato[1],
      departamento: mockDepartamento[1],
      no_contrato: "CTR014",
      fecha_entrada: "2023-02-01",
      fecha_firmado: "2023-02-05",
      fecha_vencido: "2024-02-05",
      valor_cup: 19000,
      monto_vencimiento_cup: 3800,
      valor_cl: 16000,
      monto_vencimiento_cl: 3200,
      valor_usd: 950,
      monto_vencimiento_usd: 190,
      observaciones: "Servicios vencidos",
      no_comite_contratacion: 14,
      fecha_comite_contratacion: "2023-01-25",
      no_acuerdo_comite_contratacion: 114,
      fecha_acuerdo_comite_contratacion: "2023-01-27",
      no_comite_administracion: 214,
      fecha_comite_administracion: "2023-01-29",
      monto_total: 32000,
      estado: "Vencido"
    },
    {
      id: 15,
      vigencia: mockVigenciaContrato[2],
      proveedor: mockProveedor[2],
      tipo_contrato: mockTipoContrato[2],
      departamento: mockDepartamento[2],
      no_contrato: "CTR015",
      fecha_entrada: "2023-03-01",
      fecha_firmado: "2023-03-05",
      fecha_vencido: "2024-03-05",
      valor_cup: 20000,
      monto_vencimiento_cup: 4000,
      valor_cl: 17000,
      monto_vencimiento_cl: 3400,
      valor_usd: 1000,
      monto_vencimiento_usd: 200,
      observaciones: "Consultoría vencida",
      no_comite_contratacion: 15,
      fecha_comite_contratacion: "2023-02-25",
      no_acuerdo_comite_contratacion: 115,
      fecha_acuerdo_comite_contratacion: "2023-02-27",
      no_comite_administracion: 215,
      fecha_comite_administracion: "2023-03-01",
      monto_total: 35000,
      estado: "Vencido"
    }
  ];
  
  export const mockEjecucionContrato = [
    { id: 1, proveedor: mockProveedor[0], contrato: mockContrato[0], costo_cup: 5000, costo_cl: 4000, trabajo_ejecutado: "Entrega de suministros", fecha_ejecucion: "2025-03-01" },
    { id: 2, proveedor: mockProveedor[1], contrato: mockContrato[1], costo_cup: 6000, costo_cl: 4500, trabajo_ejecutado: "Servicios educativos", fecha_ejecucion: "2025-04-01" },
    { id: 1, proveedor: mockProveedor[0], contrato: mockContrato[0], costo_cup: 5000, costo_cl: 4000, trabajo_ejecutado: "Entrega de suministros", fecha_ejecucion: "2023-03-01" },
    { id: 2, proveedor: mockProveedor[1], contrato: mockContrato[1], costo_cup: 6000, costo_cl: 4500, trabajo_ejecutado: "Servicios educativos", fecha_ejecucion: "2024-04-01" },
    { id: 3, proveedor: mockProveedor[2], contrato: mockContrato[2], costo_cup: 7000, costo_cl: 5000, trabajo_ejecutado: "Construcción carretera", fecha_ejecucion: "2025-05-01" },
    { id: 4, proveedor: mockProveedor[0], contrato: mockContrato[3], costo_cup: 4000, costo_cl: 3000, trabajo_ejecutado: "Consultoría técnica", fecha_ejecucion: "2023-06-01" },
    { id: 5, proveedor: mockProveedor[1], contrato: mockContrato[4], costo_cup: 8000, costo_cl: 6000, trabajo_ejecutado: "Mantenimiento", fecha_ejecucion: "2024-07-01" }
  ];
