import { Suplemento } from 'app/models/Type';
import { mockProveedor, mockTipoContrato, mockVigenciaContrato, mockDepartamento } from '../contrato-fake/fake';

export const mockSuplemento: Suplemento[] = [
  {
    id: 1,
    vigencia_id: 1,
    proveedor_id: 1,
    tipo_contrato_id: 1,
    no_contrato_id: 1,
    departamento_id: 1,
    fecha_entrada: new Date('2023-01-01'),
    fecha_firmado: new Date('2023-01-10'),
    valor_cup: 10000,
    monto_vencimiento_cup: 5000,
    monto_vencimiento_cl: 0,
    valor_usd: 400,
    monto_vencimiento_usd: 200,
    observaciones: 'Primer suplemento',
    no_contrato_contratacion: 12345,
    fecha_comite_contratacion: new Date('2023-01-15'),
    no_comite_contratacion: 1,
    no_acuerdo_comite_contratacion: 101,
    fecha_comite_administracion: new Date('2023-01-20'),
    no_comite_administracion: 2,
    no_acuerdo_comite_administracion: 202,
    fecha_vencido: new Date('2024-01-01'),
    valor_monto_restante: 3000,
    vigencia: mockVigenciaContrato[0],
    proveedor: mockProveedor[0],
    tipo_contrato: mockTipoContrato[0],
    departamento: mockDepartamento[0]
  },
  {
    id: 2,
    vigencia_id: 2,
    proveedor_id: 2,
    tipo_contrato_id: 2,
    no_contrato_id: 2,
    departamento_id: 2,
    fecha_entrada: new Date('2023-02-01'),
    fecha_firmado: new Date('2023-02-10'),
    valor_cup: 20000,
    monto_vencimiento_cup: 10000,
    monto_vencimiento_cl: 0,
    valor_usd: 800,
    monto_vencimiento_usd: 400,
    observaciones: 'Segundo suplemento',
    no_contrato_contratacion: 67890,
    fecha_comite_contratacion: new Date('2023-02-15'),
    no_comite_contratacion: 3,
    no_acuerdo_comite_contratacion: 102,
    fecha_comite_administracion: new Date('2023-02-20'),
    no_comite_administracion: 4,
    no_acuerdo_comite_administracion: 203,
    fecha_vencido: new Date('2024-02-01'),
    valor_monto_restante: 6000,
    vigencia: mockVigenciaContrato[1],
    proveedor: mockProveedor[1],
    tipo_contrato: mockTipoContrato[1],
    departamento: mockDepartamento[1]
  }
];
