name: Deploy Angular App to GitHub Pages

on:
  push:
    branches: [ main, develop ]  # Ajusta según la rama que quieras desplegar

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build -- --base-href=/contratacion-front/
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/contratacion-front  # Ajusta al nombre de tu carpeta de salida
          branch: gh-pages  # La rama donde se publicará el código compilado
